load("@bazel_env.bzl", "bazel_env")
load("@multitool//:tools.bzl", "TOOLS")
load("@rules_go//go:def.bzl", "TOOLS_NOGO", "nogo")

bazel_env(
    name = "env",
    tags = ["manual"],
    tools = {
        "buildifier": TOOLS["buildifier"],
        "go": "@rules_go//go",
        "golangci-lint": TOOLS["golangci-lint"],
        "pre-commit": "@pre-commit//file",
    },
    watch_files = {
        "_common": ["MODULE.bazel"],
        "buildifier": ["multitool.lock.json"],
        "go": ["go.mod"],
        "golangci-lint": ["multitool.lock.json"],
    },
)

nogo(
    name = "nogo",
    visibility = ["//visibility:public"],
    deps = TOOLS_NOGO,
)
